language: go
sudo: false
go:
  - 1.4.3
  - 1.5.3
  - 1.6
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
script:
  - time go build -v
install:
  - go get github.com/stretchr/testify
  - go get -v ./...
  - go clean
