language: go

dist: bionic

env:
  global:
    - CACHE_NAME=${TRAVIS_ARCH}
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    - HUGO_BUILD_TAGS=extended

git:
  depth: false
go:
  - "1.14.8"
  - "1.15.1"
  - master

arch:
  - amd64
  - arm64

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - go: master
    - arch: arm64
  fast_finish: true
  exclude:
    - os: windows
      go: master
    - arch: arm64
      os: osx
    - arch: arm64
      os: windows

cache:
  directories:
    - $HOME/gopath/pkg/mod
    - $HOME/.cache/go-build
    - $HOME/Library/Caches/go-build
    - $HOME/AppData/Local/go-build

before_install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin":"$PATH";
  - echo "Home is $HOME";
  - echo "Path is $PATH";
  - df -h
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then
        choco install mingw -y;
        choco install -y --force nodejs;
        curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/1.0.0-beta.5/sass_embedded-1.0.0-beta.5-windows-x64.zip;
        echo "5e65c0d8cbe038b6a120a3e7f390ad731708998f37c2de8ba565c51746a4588c  sass_embedded-1.0.0-beta.5-windows-x64.zip" | sha256sum -c - || exit 1;
        unzip sass_embedded-1.0.0-beta.5-windows-x64.zip -d $HOME/bin;
        export PATH=/c/tools/mingw64/bin:"$PATH";
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/1.0.0-beta.5/sass_embedded-1.0.0-beta.5-macos-x64.tar.gz;
        echo "47b55a39126155f89fdfb8eea7c19ba976b3f6fadbdb6867e5582a18137bd180  sass_embedded-1.0.0-beta.5-macos-x64.zip" | sha256sum -c - || exit 1;
        tar -xvf sass_embedded-1.0.0-beta.5-macos-x64.tar.gz -C $HOME/bin;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/1.0.0-beta.5/sass_embedded-1.0.0-beta.5-linux-x64.tar.gz;
        echo "642738beaea4ef1b9168446bc105267a2948a5e939537f5bd5afb48159140a44  sass_embedded-1.0.0-beta.5-linux-x64.zip" | sha256sum -c - || exit 1;
        tar -xvf sass_embedded-1.0.0-beta.5-linux-x64.tar.gz -C $HOME/bin;
    fi
  - ls $HOME/bin;
  - gem install asciidoctor
  - type asciidoctor

install:
  - mkdir -p $HOME/src
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/hugo
  - cd $HOME/src/hugo
  - go get github.com/magefile/mage

script:
  - go mod download
  - go mod verify
  - mage -v test
  - if [ "$TRAVIS_ARCH" = "amd64" ]; then
        mage -v check;
    else
        HUGO_TIMEOUT=30000 mage -v check;
    fi
  - mage -v hugo
  - HUGO_IGNOREERRORS=error-remote-getjson ./hugo -s docs/
  - HUGO_IGNOREERRORS=error-remote-getjson ./hugo --renderToMemory -s docs/
  - df -h
