# TODO1 delete me.

[[plugins]]
    name = "hugo-sql-content"
    [[plugins.params]]
        query = "SELECT * FROM pages WHERE path = ?"

[[pages]]
    kind = "section"
    path = "my-section"
    title = "My Section"
    date = 2020-01-01T12:00:00Z
    lastMod = 2021-01-01T12:00:00Z
    publishDate = 2022-01-01T12:00:00Z
    expiryDate = 2032-01-01T12:00:00Z
    weight = 10
    description = "Welcome to My section."
    content = """
    This is my **section**.
    """

    [[pages.resources]]
        path      = "bootstrap.min.css"
        mediaType = "text/css"
        url       = "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"

    [[pages.resources]]
        path      = "sunset.jpg"
        mediaType = "image/jpg"
        url       = "file:///Users/bep/Downloads/IMG_20181225_123456.jpg"

[[pages]]
    path  = "my-section/my-page"
    title = "My Page"

    # hugo.toml.

[[plugins]]
    type   = "content"
    module = "github.com/gohugoio/plugins-content-sql"

[module]
    configNamespace = "hugo-sql-content"
    [[module.imports]]
        path = 'github.com/gohugoio/plugins-content-sql'

[params.hugo-sql-content]
    dburl = "sqlite3://:memory:"
