on:
  push:
    branches: [ master ]
  pull_request:
name: TestDartSassV1
env:
    GOPROXY: https://proxy.golang.org
    GO111MODULE: on
    DART_SASS_VERSION: 1.62.1
    DART_SASS_SHA_LINUX: 3574da75a7322a539034648b8ff84ff2cca162eb924d72b663d718cd3936f075
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
        cache: true
        cache-dependency-path: |
          **/go.sum
          **/go.mod
    - name: Install Ruby
      uses: ruby/setup-ruby@v1.171.0
      with:
        ruby-version: '2.7' 
        bundler-cache: true #
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Mage
      run: go install github.com/magefile/mage@v1.15.0
    - name: Install asciidoctor
      uses: reitzig/actions-asciidoctor@v2.0.1
    - name: Install docutils
      run: |
        pip install docutils
        rst2html.py --version
    - if: matrix.os == 'ubuntu-latest'
      name: Install pandoc on Linux
      run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
    - if: matrix.os == 'macos-latest'
      run: |
        brew install pandoc
    - if: matrix.os == 'windows-latest'
      run: |
        Choco-Install -PackageName pandoc
    - run: pandoc -v
    - name: Install dart-sass-embedded Linux
      run: |
        echo "Install Dart Sass version ${DART_SASS_VERSION} ..."
        curl -LJO "https://github.com/sass/dart-sass-embedded/releases/download/${DART_SASS_VERSION}/sass_embedded-${DART_SASS_VERSION}-linux-x64.tar.gz";
        echo "${DART_SASS_SHA_LINUX}  sass_embedded-${DART_SASS_VERSION}-linux-x64.tar.gz" | sha256sum -c;
        tar -xvf "sass_embedded-${DART_SASS_VERSION}-linux-x64.tar.gz";
        echo "$GITHUB_WORKSPACE/sass_embedded/" >> $GITHUB_PATH
    - name: Check
      run: |
        dart-sass-embedded --version
        mage -v check;
      env:
        HUGO_BUILD_TAGS: extended
